<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios = [
            ['departamentos_id' => 1, 'codigo' => '01', 'nombre' => 'Guatemala'],
            ['departamentos_id' => 1, 'codigo' => '02', 'nombre' => 'Santa Catarina Pinula'],
            ['departamentos_id' => 1, 'codigo' => '03', 'nombre' => 'San José Pinula'],
            ['departamentos_id' => 1, 'codigo' => '04', 'nombre' => 'San José del Golfo'],
            ['departamentos_id' => 1, 'codigo' => '05', 'nombre' => 'Palencia'],
            ['departamentos_id' => 1, 'codigo' => '06', 'nombre' => 'Chinautla'],
            ['departamentos_id' => 1, 'codigo' => '07', 'nombre' => 'San Pedro Ayampuc'],
            ['departamentos_id' => 1, 'codigo' => '08', 'nombre' => 'Mixco'],
            ['departamentos_id' => 1, 'codigo' => '09', 'nombre' => 'San Pedro Sacatepéquez'],
            ['departamentos_id' => 1, 'codigo' => '10', 'nombre' => 'San Juan Sacatepéquez'],
            ['departamentos_id' => 1, 'codigo' => '11', 'nombre' => 'San Raymundo'],
            ['departamentos_id' => 1, 'codigo' => '12', 'nombre' => 'Chuarrancho'],
            ['departamentos_id' => 1, 'codigo' => '13', 'nombre' => 'Fraijanes'],
            ['departamentos_id' => 1, 'codigo' => '14', 'nombre' => 'Amatitlán'],
            ['departamentos_id' => 1, 'codigo' => '15', 'nombre' => 'Villa Nueva'],
            ['departamentos_id' => 1, 'codigo' => '16', 'nombre' => 'Villa Canales'],
            ['departamentos_id' => 1, 'codigo' => '17', 'nombre' => 'San Miguel Petapa'],

            /* -- 02 El Progreso --  */
            ['departamentos_id' => 2, 'codigo' => '01', 'nombre' => 'Guastatoya'],
            ['departamentos_id' => 2, 'codigo' => '02', 'nombre' => 'Morazán'],
            ['departamentos_id' => 2, 'codigo' => '03', 'nombre' => 'San Agustín Acasaguastlán'],
            ['departamentos_id' => 2, 'codigo' => '04', 'nombre' => 'San Cristóbal Acasaguastlán'],
            ['departamentos_id' => 2, 'codigo' => '05', 'nombre' => 'El Jícaro'],
            ['departamentos_id' => 2, 'codigo' => '06', 'nombre' => 'Sansare'],
            ['departamentos_id' => 2, 'codigo' => '07', 'nombre' => 'Sanarate'],
            ['departamentos_id' => 2, 'codigo' => '08', 'nombre' => 'San Antonio La Paz'],

            /* -- 03 Sacatepéquez --  */
            ['departamentos_id' => 3, 'codigo' => '01', 'nombre' => 'Antigua Guatemala'],
            ['departamentos_id' => 3, 'codigo' => '02', 'nombre' => 'Jocotenango'],
            ['departamentos_id' => 3, 'codigo' => '03', 'nombre' => 'Pastores'],
            ['departamentos_id' => 3, 'codigo' => '04', 'nombre' => 'Sumpango'],
            ['departamentos_id' => 3, 'codigo' => '05', 'nombre' => 'Santo Domingo Xenacoj'],
            ['departamentos_id' => 3, 'codigo' => '06', 'nombre' => 'Santiago Sacatepéquez'],
            ['departamentos_id' => 3, 'codigo' => '07', 'nombre' => 'San Bartolomé Milpas Altas'],
            ['departamentos_id' => 3, 'codigo' => '08', 'nombre' => 'San Lucas Sacatepéquez'],
            ['departamentos_id' => 3, 'codigo' => '09', 'nombre' => 'Santa Lucía Milpas Altas'],
            ['departamentos_id' => 3, 'codigo' => '10', 'nombre' => 'Magdalena Milpas Altas'],
            ['departamentos_id' => 3, 'codigo' => '11', 'nombre' => 'Santa María de Jesús'],
            ['departamentos_id' => 3, 'codigo' => '12', 'nombre' => 'Ciudad Vieja'],
            ['departamentos_id' => 3, 'codigo' => '13', 'nombre' => 'San Miguel Dueñas'],
            ['departamentos_id' => 3, 'codigo' => '14', 'nombre' => 'San Juan Alotenango'],
            ['departamentos_id' => 3, 'codigo' => '15', 'nombre' => 'San Antonio Aguas Calientes'],
            ['departamentos_id' => 3, 'codigo' => '16', 'nombre' => 'Santa Catarina Barahona'],

            /* -- 04 Chimaltenango --  */
            ['departamentos_id' => 4, 'codigo' => '01', 'nombre' => 'Chimaltenango'],
            ['departamentos_id' => 4, 'codigo' => '02', 'nombre' => 'San José Poaquíl'],
            ['departamentos_id' => 4, 'codigo' => '03', 'nombre' => 'San Martín Jilotepeque'],
            ['departamentos_id' => 4, 'codigo' => '04', 'nombre' => 'San Juan Comalapa'],
            ['departamentos_id' => 4, 'codigo' => '05', 'nombre' => 'Santa Apolonia'],
            ['departamentos_id' => 4, 'codigo' => '06', 'nombre' => 'Tecpán Guatemala'],
            ['departamentos_id' => 4, 'codigo' => '07', 'nombre' => 'Patzún'],
            ['departamentos_id' => 4, 'codigo' => '08', 'nombre' => 'San Miguel Pochuta'],
            ['departamentos_id' => 4, 'codigo' => '09', 'nombre' => 'Patzicía'],
            ['departamentos_id' => 4, 'codigo' => '10', 'nombre' => 'Santa Cruz Balanyá'],
            ['departamentos_id' => 4, 'codigo' => '11', 'nombre' => 'Acatenango'],
            ['departamentos_id' => 4, 'codigo' => '12', 'nombre' => 'San Pedro Yepocapa'],
            ['departamentos_id' => 4, 'codigo' => '13', 'nombre' => 'San Andrés Itzapa'],
            ['departamentos_id' => 4, 'codigo' => '14', 'nombre' => 'Parramos'],
            ['departamentos_id' => 4, 'codigo' => '15', 'nombre' => 'Zaragoza'],
            ['departamentos_id' => 4, 'codigo' => '16', 'nombre' => 'El Tejar'],

            /* -- 05 Escuintla --  */
            ['departamentos_id' => 5, 'codigo' => '01', 'nombre' => 'Escuintla'],
            ['departamentos_id' => 5, 'codigo' => '02', 'nombre' => 'Santa Lucía Cotzumalguapa'],
            ['departamentos_id' => 5, 'codigo' => '03', 'nombre' => 'La Democracia'],
            ['departamentos_id' => 5, 'codigo' => '04', 'nombre' => 'Siquinalá'],
            ['departamentos_id' => 5, 'codigo' => '05', 'nombre' => 'Masagua'],
            ['departamentos_id' => 5, 'codigo' => '06', 'nombre' => 'Tiquisate'],
            ['departamentos_id' => 5, 'codigo' => '07', 'nombre' => 'La Gomera'],
            ['departamentos_id' => 5, 'codigo' => '08', 'nombre' => 'Guanagazapa'],
            ['departamentos_id' => 5, 'codigo' => '09', 'nombre' => 'San José'],
            ['departamentos_id' => 5, 'codigo' => '10', 'nombre' => 'Iztapa'],
            ['departamentos_id' => 5, 'codigo' => '11', 'nombre' => 'Palín'],
            ['departamentos_id' => 5, 'codigo' => '12', 'nombre' => 'San Vicente Pacaya'],
            ['departamentos_id' => 5, 'codigo' => '13', 'nombre' => 'Nueva Concepción'],
            ['departamentos_id' => 5, 'codigo' => '14', 'nombre' => 'Sipacate'],

            /* -- 06 Santa Rosa --  */
            ['departamentos_id' => 6, 'codigo' => '01', 'nombre' => 'Cuilapa'],
            ['departamentos_id' => 6, 'codigo' => '02', 'nombre' => 'Barberena'],
            ['departamentos_id' => 6, 'codigo' => '03', 'nombre' => 'Santa Rosa de Lima'],
            ['departamentos_id' => 6, 'codigo' => '04', 'nombre' => 'Casillas'],
            ['departamentos_id' => 6, 'codigo' => '05', 'nombre' => 'San Rafael Las Flores'],
            ['departamentos_id' => 6, 'codigo' => '06', 'nombre' => 'Oratorio'],
            ['departamentos_id' => 6, 'codigo' => '07', 'nombre' => 'San Juan Tecuaco'],
            ['departamentos_id' => 6, 'codigo' => '08', 'nombre' => 'Chiquimulilla'],
            ['departamentos_id' => 6, 'codigo' => '09', 'nombre' => 'Taxisco'],
            ['departamentos_id' => 6, 'codigo' => '10', 'nombre' => 'Santa María Ixhuatán'],
            ['departamentos_id' => 6, 'codigo' => '11', 'nombre' => 'Guazacapán'],
            ['departamentos_id' => 6, 'codigo' => '12', 'nombre' => 'Santa Cruz Naranjo'],
            ['departamentos_id' => 6, 'codigo' => '13', 'nombre' => 'Pueblo Nuevo Viñas'],
            ['departamentos_id' => 6, 'codigo' => '14', 'nombre' => 'Nueva Santa Rosa'],

            /* -- 07 Sololá --  */
            ['departamentos_id' => 7, 'codigo' => '01', 'nombre' => 'Sololá'],
            ['departamentos_id' => 7, 'codigo' => '02', 'nombre' => 'San José Chacayá'],
            ['departamentos_id' => 7, 'codigo' => '03', 'nombre' => 'Santa María Visitación'],
            ['departamentos_id' => 7, 'codigo' => '04', 'nombre' => 'Santa Lucía Utatlán'],
            ['departamentos_id' => 7, 'codigo' => '05', 'nombre' => 'Nahualá'],
            ['departamentos_id' => 7, 'codigo' => '06', 'nombre' => 'Santa Catarina Ixtahuacán'],
            ['departamentos_id' => 7, 'codigo' => '07', 'nombre' => 'Santa Clara La Laguna'],
            ['departamentos_id' => 7, 'codigo' => '08', 'nombre' => 'Concepción'],
            ['departamentos_id' => 7, 'codigo' => '09', 'nombre' => 'San Andrés Semetabaj'],
            ['departamentos_id' => 7, 'codigo' => '10', 'nombre' => 'Panajachel'],
            ['departamentos_id' => 7, 'codigo' => '11', 'nombre' => 'Santa Catarina Palopó'],
            ['departamentos_id' => 7, 'codigo' => '12', 'nombre' => 'San Antonio Palopó'],
            ['departamentos_id' => 7, 'codigo' => '13', 'nombre' => 'San Lucas Tolimán'],
            ['departamentos_id' => 7, 'codigo' => '14', 'nombre' => 'Santa Cruz La Laguna'],
            ['departamentos_id' => 7, 'codigo' => '15', 'nombre' => 'San Pablo La Laguna'],
            ['departamentos_id' => 7, 'codigo' => '16', 'nombre' => 'San Marcos La Laguna'],
            ['departamentos_id' => 7, 'codigo' => '17', 'nombre' => 'San Juan La Laguna'],
            ['departamentos_id' => 7, 'codigo' => '18', 'nombre' => 'San Pedro La Laguna'],
            ['departamentos_id' => 7, 'codigo' => '19', 'nombre' => 'Santiago Atitlán'],

            /* -- 08 Totonicapán --  */
            ['departamentos_id' => 8, 'codigo' => '01', 'nombre' => 'Totonicapán'],
            ['departamentos_id' => 8, 'codigo' => '02', 'nombre' => 'San Cristóbal Totonicapán'],
            ['departamentos_id' => 8, 'codigo' => '03', 'nombre' => 'San Francisco El Alto'],
            ['departamentos_id' => 8, 'codigo' => '04', 'nombre' => 'San Andrés Xecul'],
            ['departamentos_id' => 8, 'codigo' => '05', 'nombre' => 'Momostenango'],
            ['departamentos_id' => 8, 'codigo' => '06', 'nombre' => 'Santa María Chiquimula'],
            ['departamentos_id' => 8, 'codigo' => '07', 'nombre' => 'Santa Lucía La Reforma'],
            ['departamentos_id' => 8, 'codigo' => '08', 'nombre' => 'San Bartolo Aguas Calientes'],

            /* -- 09 Quetzaltenango --  */
            ['departamentos_id' => 9, 'codigo' => '01', 'nombre' => 'Quetzaltenango'],
            ['departamentos_id' => 9, 'codigo' => '02', 'nombre' => 'Salcajá'],
            ['departamentos_id' => 9, 'codigo' => '03', 'nombre' => 'San Juan Olintepeque'],
            ['departamentos_id' => 9, 'codigo' => '04', 'nombre' => 'San Carlos Sija'],
            ['departamentos_id' => 9, 'codigo' => '05', 'nombre' => 'Sibilia'],
            ['departamentos_id' => 9, 'codigo' => '06', 'nombre' => 'Cabricán'],
            ['departamentos_id' => 9, 'codigo' => '07', 'nombre' => 'Cajolá'],
            ['departamentos_id' => 9, 'codigo' => '08', 'nombre' => 'San Miguel Sigüilá'],
            ['departamentos_id' => 9, 'codigo' => '09', 'nombre' => 'San Juan Ostuncalco'],
            ['departamentos_id' => 9, 'codigo' => '10', 'nombre' => 'San Mateo'],
            ['departamentos_id' => 9, 'codigo' => '11', 'nombre' => 'Concepción Chiquirichapa'],
            ['departamentos_id' => 9, 'codigo' => '12', 'nombre' => 'San Martín Sacatepéquez'],
            ['departamentos_id' => 9, 'codigo' => '13', 'nombre' => 'Almolonga'],
            ['departamentos_id' => 9, 'codigo' => '14', 'nombre' => 'Cantel'],
            ['departamentos_id' => 9, 'codigo' => '15', 'nombre' => 'Huitán'],
            ['departamentos_id' => 9, 'codigo' => '16', 'nombre' => 'Zunil'],
            ['departamentos_id' => 9, 'codigo' => '17', 'nombre' => 'Colomba Costa Cuca'],
            ['departamentos_id' => 9, 'codigo' => '18', 'nombre' => 'San Francisco La Unión'],
            ['departamentos_id' => 9, 'codigo' => '19', 'nombre' => 'El Palmar'],
            ['departamentos_id' => 9, 'codigo' => '20', 'nombre' => 'Coatepeque'],
            ['departamentos_id' => 9, 'codigo' => '21', 'nombre' => 'Génova'],
            ['departamentos_id' => 9, 'codigo' => '22', 'nombre' => 'Flores Costa Cuca'],
            ['departamentos_id' => 9, 'codigo' => '23', 'nombre' => 'La Esperanza'],
            ['departamentos_id' => 9, 'codigo' => '24', 'nombre' => 'Palestina de Los Altos'],

            /* -- 10 Suchitepéquez --  */
            ['departamentos_id' => 10, 'codigo' => '01', 'nombre' => 'Mazatenango'],
            ['departamentos_id' => 10, 'codigo' => '02', 'nombre' => 'Cuyotenango'],
            ['departamentos_id' => 10, 'codigo' => '03', 'nombre' => 'San Francisco Zapotitlán'],
            ['departamentos_id' => 10, 'codigo' => '04', 'nombre' => 'San Bernardino'],
            ['departamentos_id' => 10, 'codigo' => '05', 'nombre' => 'San José El Ídolo'],
            ['departamentos_id' => 10, 'codigo' => '06', 'nombre' => 'Santo Domingo Suchitepéquez'],
            ['departamentos_id' => 10, 'codigo' => '07', 'nombre' => 'San Lorenzo'],
            ['departamentos_id' => 10, 'codigo' => '08', 'nombre' => 'Samayac'],
            ['departamentos_id' => 10, 'codigo' => '09', 'nombre' => 'San Pablo Jocopilas'],
            ['departamentos_id' => 10, 'codigo' => '10', 'nombre' => 'San Antonio Suchitepéquez'],
            ['departamentos_id' => 10, 'codigo' => '11', 'nombre' => 'San Miguel Panán'],
            ['departamentos_id' => 10, 'codigo' => '12', 'nombre' => 'San Gabriel'],
            ['departamentos_id' => 10, 'codigo' => '13', 'nombre' => 'Chicacao'],
            ['departamentos_id' => 10, 'codigo' => '14', 'nombre' => 'Patulul'],
            ['departamentos_id' => 10, 'codigo' => '15', 'nombre' => 'Santa Bárbara'],
            ['departamentos_id' => 10, 'codigo' => '16', 'nombre' => 'San Juan Bautista'],
            ['departamentos_id' => 10, 'codigo' => '17', 'nombre' => 'Santo Tomás La Unión'],
            ['departamentos_id' => 10, 'codigo' => '18', 'nombre' => 'Zunilito'],
            ['departamentos_id' => 10, 'codigo' => '19', 'nombre' => 'Pueblo Nuevo'],
            ['departamentos_id' => 10, 'codigo' => '20', 'nombre' => 'Río Bravo'],
            ['departamentos_id' => 10, 'codigo' => '21', 'nombre' => 'San José La Máquina'],

            /* -- 11 Retalhuleu --  */
            ['departamentos_id' => 11, 'codigo' => '01', 'nombre' => 'Retalhuleu'],
            ['departamentos_id' => 11, 'codigo' => '02', 'nombre' => 'San Sebastián'],
            ['departamentos_id' => 11, 'codigo' => '03', 'nombre' => 'Santa Cruz Muluá'],
            ['departamentos_id' => 11, 'codigo' => '04', 'nombre' => 'San Martín Zapotitlán'],
            ['departamentos_id' => 11, 'codigo' => '05', 'nombre' => 'San Felipe'],
            ['departamentos_id' => 11, 'codigo' => '06', 'nombre' => 'San Andrés Villa Seca'],
            ['departamentos_id' => 11, 'codigo' => '07', 'nombre' => 'Champerico'],
            ['departamentos_id' => 11, 'codigo' => '08', 'nombre' => 'Nuevo San Carlos'],
            ['departamentos_id' => 11, 'codigo' => '09', 'nombre' => 'El Asintal'],

            /* -- 12 San Marcos --  */
            ['departamentos_id' => 12, 'codigo' => '01', 'nombre' => 'San Marcos'],
            ['departamentos_id' => 12, 'codigo' => '02', 'nombre' => 'San Pedro Sacatepéquez'],
            ['departamentos_id' => 12, 'codigo' => '03', 'nombre' => 'San Antonio Sacatepéquez'],
            ['departamentos_id' => 12, 'codigo' => '04', 'nombre' => 'Comitancillo'],
            ['departamentos_id' => 12, 'codigo' => '05', 'nombre' => 'San Miguel Ixtahuacán'],
            ['departamentos_id' => 12, 'codigo' => '06', 'nombre' => 'Concepción Tutuapa'],
            ['departamentos_id' => 12, 'codigo' => '07', 'nombre' => 'Tacaná'],
            ['departamentos_id' => 12, 'codigo' => '08', 'nombre' => 'Sibinal'],
            ['departamentos_id' => 12, 'codigo' => '09', 'nombre' => 'Tajumulco'],
            ['departamentos_id' => 12, 'codigo' => '10', 'nombre' => 'Tejutla'],
            ['departamentos_id' => 12, 'codigo' => '11', 'nombre' => 'San Rafael Pie De La Cuesta'],
            ['departamentos_id' => 12, 'codigo' => '12', 'nombre' => 'Nuevo Progreso'],
            ['departamentos_id' => 12, 'codigo' => '13', 'nombre' => 'El Tumbador'],
            ['departamentos_id' => 12, 'codigo' => '14', 'nombre' => 'San José El Rodeo'],
            ['departamentos_id' => 12, 'codigo' => '15', 'nombre' => 'Malacatán'],
            ['departamentos_id' => 12, 'codigo' => '16', 'nombre' => 'Catarina'],
            ['departamentos_id' => 12, 'codigo' => '17', 'nombre' => 'Ayutla'],
            ['departamentos_id' => 12, 'codigo' => '18', 'nombre' => 'Ocós'],
            ['departamentos_id' => 12, 'codigo' => '19', 'nombre' => 'San Pablo'],
            ['departamentos_id' => 12, 'codigo' => '20', 'nombre' => 'El Quetzal'],
            ['departamentos_id' => 12, 'codigo' => '21', 'nombre' => 'La Reforma'],
            ['departamentos_id' => 12, 'codigo' => '22', 'nombre' => 'Pajapita'],
            ['departamentos_id' => 12, 'codigo' => '23', 'nombre' => 'Ixchiguán'],
            ['departamentos_id' => 12, 'codigo' => '24', 'nombre' => 'San José Ojetenam'],
            ['departamentos_id' => 12, 'codigo' => '25', 'nombre' => 'San Cristóbal Cucho'],
            ['departamentos_id' => 12, 'codigo' => '26', 'nombre' => 'Sipacapa'],
            ['departamentos_id' => 12, 'codigo' => '27', 'nombre' => 'Esquipulas Palo Gordo'],
            ['departamentos_id' => 12, 'codigo' => '28', 'nombre' => 'Río Blanco'],
            ['departamentos_id' => 12, 'codigo' => '29', 'nombre' => 'San Lorenzo'],
            ['departamentos_id' => 12, 'codigo' => '30', 'nombre' => 'La Blanca'],

            /* -- 13 Huehuetenango --  */
            ['departamentos_id' => 13, 'codigo' => '01', 'nombre' => 'Huehuetenango'],
            ['departamentos_id' => 13, 'codigo' => '02', 'nombre' => 'Chiantla'],
            ['departamentos_id' => 13, 'codigo' => '03', 'nombre' => 'Malacatancito'],
            ['departamentos_id' => 13, 'codigo' => '04', 'nombre' => 'Cuilco'],
            ['departamentos_id' => 13, 'codigo' => '05', 'nombre' => 'Nentón'],
            ['departamentos_id' => 13, 'codigo' => '06', 'nombre' => 'San Pedro Nécta'],
            ['departamentos_id' => 13, 'codigo' => '07', 'nombre' => 'Jacaltenango'],
            ['departamentos_id' => 13, 'codigo' => '08', 'nombre' => 'San Pedro Soloma'],
            ['departamentos_id' => 13, 'codigo' => '09', 'nombre' => 'San Ildefonso Ixtahuacán'],
            ['departamentos_id' => 13, 'codigo' => '10', 'nombre' => 'Santa Bárbara'],
            ['departamentos_id' => 13, 'codigo' => '11', 'nombre' => 'La Libertad'],
            ['departamentos_id' => 13, 'codigo' => '12', 'nombre' => 'La Democracia'],
            ['departamentos_id' => 13, 'codigo' => '13', 'nombre' => 'San Miguel Acatán'],
            ['departamentos_id' => 13, 'codigo' => '14', 'nombre' => 'San Rafael La Independencia'],
            ['departamentos_id' => 13, 'codigo' => '15', 'nombre' => 'Todos Santos Cuchumatán'],
            ['departamentos_id' => 13, 'codigo' => '16', 'nombre' => 'San Juan Atitán'],
            ['departamentos_id' => 13, 'codigo' => '17', 'nombre' => 'Santa Eulalia'],
            ['departamentos_id' => 13, 'codigo' => '18', 'nombre' => 'San Mateo Ixtatán'],
            ['departamentos_id' => 13, 'codigo' => '19', 'nombre' => 'Colotenango'],
            ['departamentos_id' => 13, 'codigo' => '20', 'nombre' => 'San Sebastián Huehuetenango'],
            ['departamentos_id' => 13, 'codigo' => '21', 'nombre' => 'Tectitán'],
            ['departamentos_id' => 13, 'codigo' => '22', 'nombre' => 'Concepción Huista'],
            ['departamentos_id' => 13, 'codigo' => '23', 'nombre' => 'San Juan Ixcoy'],
            ['departamentos_id' => 13, 'codigo' => '24', 'nombre' => 'San Antonio Huista'],
            ['departamentos_id' => 13, 'codigo' => '25', 'nombre' => 'San Sebastián Coatán'],
            ['departamentos_id' => 13, 'codigo' => '26', 'nombre' => 'Santa Cruz Barillas'],
            ['departamentos_id' => 13, 'codigo' => '27', 'nombre' => 'Aguacatán'],
            ['departamentos_id' => 13, 'codigo' => '28', 'nombre' => 'San Rafael Pétzal'],
            ['departamentos_id' => 13, 'codigo' => '29', 'nombre' => 'San Gaspar Ixchil'],
            ['departamentos_id' => 13, 'codigo' => '30', 'nombre' => 'Santiago Chimaltenango'],
            ['departamentos_id' => 13, 'codigo' => '31', 'nombre' => 'Santa Ana Huista'],
            ['departamentos_id' => 13, 'codigo' => '32', 'nombre' => 'Unión Cantinil'],
            ['departamentos_id' => 13, 'codigo' => '33', 'nombre' => 'Petapán'],

            /* -- 14 Quiché --  */
            ['departamentos_id' => 14, 'codigo' => '01', 'nombre' => 'Santa Cruz del Quiché'],
            ['departamentos_id' => 14, 'codigo' => '02', 'nombre' => 'Chiché'],
            ['departamentos_id' => 14, 'codigo' => '03', 'nombre' => 'Chinique'],
            ['departamentos_id' => 14, 'codigo' => '04', 'nombre' => 'Zacualpa'],
            ['departamentos_id' => 14, 'codigo' => '05', 'nombre' => 'Chajul'],
            ['departamentos_id' => 14, 'codigo' => '06', 'nombre' => 'Santo Tomás Chichicastenango'],
            ['departamentos_id' => 14, 'codigo' => '07', 'nombre' => 'Patzité'],
            ['departamentos_id' => 14, 'codigo' => '08', 'nombre' => 'San Antonio Ilotenango'],
            ['departamentos_id' => 14, 'codigo' => '09', 'nombre' => 'San Pedro Jocopilas'],
            ['departamentos_id' => 14, 'codigo' => '10', 'nombre' => 'Cunén'],
            ['departamentos_id' => 14, 'codigo' => '11', 'nombre' => 'San Juan Cotzal'],
            ['departamentos_id' => 14, 'codigo' => '12', 'nombre' => 'Joyabaj'],
            ['departamentos_id' => 14, 'codigo' => '13', 'nombre' => 'Santa María Nebaj'],
            ['departamentos_id' => 14, 'codigo' => '14', 'nombre' => 'San Andrés Sajcabajá'],
            ['departamentos_id' => 14, 'codigo' => '15', 'nombre' => 'San Miguel Uspantán'],
            ['departamentos_id' => 14, 'codigo' => '16', 'nombre' => 'Sacapulas'],
            ['departamentos_id' => 14, 'codigo' => '17', 'nombre' => 'San Bartolomé Jocotenango'],
            ['departamentos_id' => 14, 'codigo' => '18', 'nombre' => 'Canillá'],
            ['departamentos_id' => 14, 'codigo' => '19', 'nombre' => 'Chicamán'],
            ['departamentos_id' => 14, 'codigo' => '20', 'nombre' => 'Ixcán'],
            ['departamentos_id' => 14, 'codigo' => '21', 'nombre' => 'Pachalum'],

            /* -- 15 Baja Verapaz --  */
            ['departamentos_id' => 15, 'codigo' => '01', 'nombre' => 'Salamá'],
            ['departamentos_id' => 15, 'codigo' => '02', 'nombre' => 'San Miguel Chicaj'],
            ['departamentos_id' => 15, 'codigo' => '03', 'nombre' => 'Rabinal'],
            ['departamentos_id' => 15, 'codigo' => '04', 'nombre' => 'Cubulco'],
            ['departamentos_id' => 15, 'codigo' => '05', 'nombre' => 'Granados'],
            ['departamentos_id' => 15, 'codigo' => '06', 'nombre' => 'Santa Cruz El Chol'],
            ['departamentos_id' => 15, 'codigo' => '07', 'nombre' => 'San Jerónimo'],
            ['departamentos_id' => 15, 'codigo' => '08', 'nombre' => 'Purulhá'],

            /* -- 16 Alta Verapaz --  */
            ['departamentos_id' => 16, 'codigo' => '01', 'nombre' => 'Cobán'],
            ['departamentos_id' => 16, 'codigo' => '02', 'nombre' => 'Santa Cruz Verapaz'],
            ['departamentos_id' => 16, 'codigo' => '03', 'nombre' => 'San Cristóbal Verapaz'],
            ['departamentos_id' => 16, 'codigo' => '04', 'nombre' => 'Tactic'],
            ['departamentos_id' => 16, 'codigo' => '05', 'nombre' => 'Tamahú'],
            ['departamentos_id' => 16, 'codigo' => '06', 'nombre' => 'Tucurú'],
            ['departamentos_id' => 16, 'codigo' => '07', 'nombre' => 'Panzós'],
            ['departamentos_id' => 16, 'codigo' => '08', 'nombre' => 'Senahú'],
            ['departamentos_id' => 16, 'codigo' => '09', 'nombre' => 'San Pedro Carchá'],
            ['departamentos_id' => 16, 'codigo' => '10', 'nombre' => 'San Juan Chamelco'],
            ['departamentos_id' => 16, 'codigo' => '11', 'nombre' => 'San Agustín Lanquín'],
            ['departamentos_id' => 16, 'codigo' => '12', 'nombre' => 'Santa María Cahabón'],
            ['departamentos_id' => 16, 'codigo' => '13', 'nombre' => 'Chisec'],
            ['departamentos_id' => 16, 'codigo' => '14', 'nombre' => 'Chahal'],
            ['departamentos_id' => 16, 'codigo' => '15', 'nombre' => 'Fray Bartolomé De Las Casas'],
            ['departamentos_id' => 16, 'codigo' => '16', 'nombre' => 'Santa Catarina La Tinta'],
            ['departamentos_id' => 16, 'codigo' => '17', 'nombre' => 'Raxruhá'],

            /* -- 17 Petén --  */
            ['departamentos_id' => 17, 'codigo' => '01', 'nombre' => 'Flores'],
            ['departamentos_id' => 17, 'codigo' => '02', 'nombre' => 'San José'],
            ['departamentos_id' => 17, 'codigo' => '03', 'nombre' => 'San Benito'],
            ['departamentos_id' => 17, 'codigo' => '04', 'nombre' => 'San Andrés'],
            ['departamentos_id' => 17, 'codigo' => '05', 'nombre' => 'La Libertad'],
            ['departamentos_id' => 17, 'codigo' => '06', 'nombre' => 'San Francisco'],
            ['departamentos_id' => 17, 'codigo' => '07', 'nombre' => 'Santa Ana'],
            ['departamentos_id' => 17, 'codigo' => '08', 'nombre' => 'Dolores'],
            ['departamentos_id' => 17, 'codigo' => '09', 'nombre' => 'San Luis'],
            ['departamentos_id' => 17, 'codigo' => '10', 'nombre' => 'Sayaxché'],
            ['departamentos_id' => 17, 'codigo' => '11', 'nombre' => 'Melchor de Mencos'],
            ['departamentos_id' => 17, 'codigo' => '12', 'nombre' => 'Poptún'],
            ['departamentos_id' => 17, 'codigo' => '13', 'nombre' => 'Las Cruces'],
            ['departamentos_id' => 17, 'codigo' => '14', 'nombre' => 'El Chal'],

            /* -- 18 Izabal --  */
            ['departamentos_id' => 18, 'codigo' => '01', 'nombre' => 'Puerto Barrios'],
            ['departamentos_id' => 18, 'codigo' => '02', 'nombre' => 'Livingston'],
            ['departamentos_id' => 18, 'codigo' => '03', 'nombre' => 'El Estor'],
            ['departamentos_id' => 18, 'codigo' => '04', 'nombre' => 'Morales'],
            ['departamentos_id' => 18, 'codigo' => '05', 'nombre' => 'Los Amates'],

            /* -- 19 Zacapa --  */
            ['departamentos_id' => 19, 'codigo' => '01', 'nombre' => 'Zacapa'],
            ['departamentos_id' => 19, 'codigo' => '02', 'nombre' => 'Estanzuela'],
            ['departamentos_id' => 19, 'codigo' => '03', 'nombre' => 'Río Hondo'],
            ['departamentos_id' => 19, 'codigo' => '04', 'nombre' => 'Gualán'],
            ['departamentos_id' => 19, 'codigo' => '05', 'nombre' => 'Teculután'],
            ['departamentos_id' => 19, 'codigo' => '06', 'nombre' => 'Usumatlán'],
            ['departamentos_id' => 19, 'codigo' => '07', 'nombre' => 'Cabañas'],
            ['departamentos_id' => 19, 'codigo' => '08', 'nombre' => 'San Diego'],
            ['departamentos_id' => 19, 'codigo' => '09', 'nombre' => 'La Unión'],
            ['departamentos_id' => 19, 'codigo' => '10', 'nombre' => 'Huité'],
            ['departamentos_id' => 19, 'codigo' => '11', 'nombre' => 'San Jorge'],

            /* -- 20 Chiquimula --  */
            ['departamentos_id' => 20, 'codigo' => '01', 'nombre' => 'Chiquimula'],
            ['departamentos_id' => 20, 'codigo' => '02', 'nombre' => 'San José la Arada'],
            ['departamentos_id' => 20, 'codigo' => '03', 'nombre' => 'San Juan Ermita'],
            ['departamentos_id' => 20, 'codigo' => '04', 'nombre' => 'Jocotán'],
            ['departamentos_id' => 20, 'codigo' => '05', 'nombre' => 'Camotán'],
            ['departamentos_id' => 20, 'codigo' => '06', 'nombre' => 'Olopa'],
            ['departamentos_id' => 20, 'codigo' => '07', 'nombre' => 'Esquipulas'],
            ['departamentos_id' => 20, 'codigo' => '08', 'nombre' => 'Concepción Las Minas'],
            ['departamentos_id' => 20, 'codigo' => '09', 'nombre' => 'Quezaltepeque'],
            ['departamentos_id' => 20, 'codigo' => '10', 'nombre' => 'San Jacinto'],
            ['departamentos_id' => 20, 'codigo' => '11', 'nombre' => 'Ipala'],

            /* -- 21 Jalapa --  */
            ['departamentos_id' => 21, 'codigo' => '01', 'nombre' => 'Jalapa'],
            ['departamentos_id' => 21, 'codigo' => '02', 'nombre' => 'San Pedro Pinula'],
            ['departamentos_id' => 21, 'codigo' => '03', 'nombre' => 'San Luis Jilotepeque'],
            ['departamentos_id' => 21, 'codigo' => '04', 'nombre' => 'San Manuel Chaparrón'],
            ['departamentos_id' => 21, 'codigo' => '05', 'nombre' => 'San Carlos Alzatate'],
            ['departamentos_id' => 21, 'codigo' => '06', 'nombre' => 'Monjas'],
            ['departamentos_id' => 21, 'codigo' => '07', 'nombre' => 'Mataquescuintla'],

            /* -- 22 Jutiapa --  */
            ['departamentos_id' => 22, 'codigo' => '01', 'nombre' => 'Jutiapa'],
            ['departamentos_id' => 22, 'codigo' => '02', 'nombre' => 'El Progreso'],
            ['departamentos_id' => 22, 'codigo' => '03', 'nombre' => 'Santa Catarina Mita'],
            ['departamentos_id' => 22, 'codigo' => '04', 'nombre' => 'Agua Blanca'],
            ['departamentos_id' => 22, 'codigo' => '05', 'nombre' => 'Asunción Mita'],
            ['departamentos_id' => 22, 'codigo' => '06', 'nombre' => 'Yupiltepeque'],
            ['departamentos_id' => 22, 'codigo' => '07', 'nombre' => 'Atescatempa'],
            ['departamentos_id' => 22, 'codigo' => '08', 'nombre' => 'Jerez'],
            ['departamentos_id' => 22, 'codigo' => '09', 'nombre' => 'El Adelanto'],
            ['departamentos_id' => 22, 'codigo' => '10', 'nombre' => 'Zapotitlán'],
            ['departamentos_id' => 22, 'codigo' => '11', 'nombre' => 'Comapa'],
            ['departamentos_id' => 22, 'codigo' => '12', 'nombre' => 'Jalpatagua'],
            ['departamentos_id' => 22, 'codigo' => '13', 'nombre' => 'Conguaco'],
            ['departamentos_id' => 22, 'codigo' => '14', 'nombre' => 'Moyuta'],
            ['departamentos_id' => 22, 'codigo' => '15', 'nombre' => 'Pasaco'],
            ['departamentos_id' => 22, 'codigo' => '16', 'nombre' => 'San José Acatempa'],
            ['departamentos_id' => 22, 'codigo' => '17', 'nombre' => 'Quesada']
        ];

        foreach ($municipios as $municipio) {
            Municipio::create([
                'departamentos_id' => $municipio['departamentos_id'],
                'codigo' => $municipio['codigo'],
                'nombre' => $municipio['nombre']
            ]);
        }
    }
}
