<?php

namespace Database\Seeders;

use App\Models\PirEmpleado;
use App\Models\PirPuesto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PirEmpleadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $empleados = [
            /* Secretaría Ejecutiva */
            ['nombre' => 'Claudinne Ogaldes Cruz', 'dir' => 1, 'puesto' => 1],
            ['nombre' => 'María Renné Santos Carballo', 'dir' => 1, 'puesto' => 69],
            ['nombre' => 'Jorge Roberto Alfaro Alvarado', 'dir' => 1, 'puesto' => 95],

            /* Subsecretaría de Coordinación y Administración */
            ['nombre' => 'Luz María Urcuyo Mendoza de García', 'dir' => 2, 'puesto' => 3],
            ['nombre' => 'Noelia Margarita Búcaro Palacios de Franco', 'dir' => 2, 'puesto' => 73],
            ['nombre' => 'Juana Margoth Colmenares Véliz', 'dir' => 2, 'puesto' => 95],

            /* Subsecretaría de Coordinación y Administración */
            ['nombre' => 'María Angela Leal Pineda', 'dir' => 3, 'puesto' => 2],
            ['nombre' => 'Ana Evelyn Cabrera Fuegos', 'dir' => 3, 'puesto' => 73],
            ['nombre' => 'Miguel Abraham Lozano Pérez', 'dir' => 3, 'puesto' => 95],
            ['nombre' => 'Ercklin Estuardo Klingenberger Ríos', 'dir' => 3, 'puesto' => 94],

            /* Dirección Administrativa */
            ['nombre' => 'Geraldine Evellyn Tobar Avalos', 'dir' => 4, 'puesto' => 93],
            ['nombre' => 'Eddie Renato Tax Ajú', 'dir' => 4, 'puesto' => 92],
            ['nombre' => 'Ruth Noemí Flores López', 'dir' => 4, 'puesto' => 75],
            ['nombre' => 'Silvia Lucía Tohom Velásquez', 'dir' => 4, 'puesto' => 6],
            ['nombre' => 'Ana Mercedez López Navarro de Cordón', 'dir' => 4, 'puesto' => 71],
            ['nombre' => 'Brayan Alexander Carrera Mencos', 'dir' => 4, 'puesto' => 8],
            ['nombre' => 'Flor de María Loaiza Díaz de Maldonado', 'dir' => 4, 'puesto' => 55],
            ['nombre' => 'Valesca Guadalupe Cheng Ortiz', 'dir' => 4, 'puesto' => 75],
            ['nombre' => 'Herny Abidán Miranda Moscoso', 'dir' => 4, 'puesto' => 18],
            ['nombre' => 'Eldy Lorena Shisshelle Ericastilla Mejía', 'dir' => 4, 'puesto' => 77],
            ['nombre' => 'Keyla Yoeli Vidal Feliz', 'dir' => 4, 'puesto' => 77],
            ['nombre' => 'Rybar Haroldo Dario Cordón Pellecer', 'dir' => 4, 'puesto' => 27],
            ['nombre' => 'Marlon Rocael López Cornel', 'dir' => 4, 'puesto' => 33],
            ['nombre' => 'Geovany Estuardo Reyes Recinos', 'dir' => 4, 'puesto' => 77],
            ['nombre' => 'Joaquin de Jesús Alvizures Gómez', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Moisés Elías Castro Pérez', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Edith Marlene Mendoza Girón', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Henry Antonio Guzmán Serén', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Ana Victoria Hernández Velásquez', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Margarita Juana Moxnay Quiché', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Pablo Oscal Montufar', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Walter Daniel Payés Guzmán', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Edwin Geovanni Rivera Virula', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Yasmín Irasema Sosa Sánchez de Molina', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Robin Haroldo Ramirez Cortéz', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Byron Omero Leal Agustin', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Marco Antonio Barahona Méndez', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Carlos Emilio Hilton Cabrera', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Neri Edilzar Cú Sam', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Hillary Nahomi Mayén Duarte', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Juan Carlos Mata Fino', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'María Alexandra Aguilar Fernández', 'dir' => 4, 'puesto' => 94],
            ['nombre' => 'Sonia Elizabeth Ixchop Alvarez', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Xiomara Adalgisa de Paz Colindres de Espinoza', 'dir' => 4, 'puesto' => 94],
            ['nombre' => 'Javier Andrés Aragón Lemus', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Juan Eduardo Lux Hernández', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Gilda Odilia Monroy Hernández de Lorenzana', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Javier Alexander Jiménez Hernández', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Dania Roxana Godoy Jiménez', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Daniela Sofía León Bosque', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Oseas Abimael Santos Ortiz', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Juan José Ramírez Higueros', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Noé Quiñonez Arana', 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'José Gabriel Sánchez Coto', 'dir' => 4, 'puesto' => 94],

            /* Dirección Financiera */
            ['nombre' => 'Kenny Benjamin Villatoro García', 'dir' => 5, 'puesto' => 93],
            ['nombre' => 'Henry Omar Reyes Méndez', 'dir' => 5, 'puesto' => 92],
            ['nombre' => 'Hercilia Abigail Marroquin López', 'dir' => 5, 'puesto' => 28],
            ['nombre' => 'Eduardo Alfredo Castillo García', 'dir' => 5, 'puesto' => 72],
            ['nombre' => 'Francisco Leonardo Méndez Puzul', 'dir' => 5, 'puesto' => 20],
            ['nombre' => 'Emilsa Meídely Isaguirre de Sagastume', 'dir' => 5, 'puesto' => 7],
            ['nombre' => 'Franklin Eduardo Zeledón Marin', 'dir' => 5, 'puesto' => 60],
            ['nombre' => 'Edy Adiel Castillo García', 'dir' => 5, 'puesto' => 72],
            ['nombre' => 'Cesibel Guevara Vargas de Marroquín', 'dir' => 5, 'puesto' => 45],
            ['nombre' => 'María De Los Angeles Milian Hernández', 'dir' => 5, 'puesto' => 9],
            ['nombre' => 'Ricardo Alejandro de León Arango', 'dir' => 5, 'puesto' => 95],
            ['nombre' => 'Bartolo Archila Orellana', 'dir' => 5, 'puesto' => 95],
            ['nombre' => 'María Candelaria Gómez Patzán', 'dir' => 5, 'puesto' => 95],
            ['nombre' => 'Luis Humberto López Salas', 'dir' => 5, 'puesto' => 95],
            ['nombre' => 'Maynor Israel Rivera Acuña', 'dir' => 5, 'puesto' => 94],
            ['nombre' => 'Hebelyn Verónica Escobedo Reynoso de Talo', 'dir' => 4, 'puesto' => 95],

            /* Dirección de Coordinacion */
            ['nombre' => 'Kelly Clemencia Lily Argueta Flores', 'dir' => 6, 'puesto' => 93],
            ['nombre' => 'Barbara Lucrecia Phefunchal Palacios', 'dir' => 6, 'puesto' => 92],
            ['nombre' => 'Claudio Armando López Cifuentes', 'dir' => 6, 'puesto' => 92],
            ['nombre' => 'Cindy Lorena Castro Monroy', 'dir' => 6, 'puesto' => 30],
            ['nombre' => 'María Alejandra Monzón Antillón', 'dir' => 6, 'puesto' => 57],
            ['nombre' => 'Vivian Lizet Obando Cortéz', 'dir' => 6, 'puesto' => 83],
            ['nombre' => 'Ingrid Esperanza Ajché Pérez de Monroy', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Marta Claudette García García de León', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Jázmin Omaidy Nicolaza Ovalle Argueta', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'José Alberto Girón Girón', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Mynor Leonel Godoy Valenzuela', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Edwin Oswaldo Saenz Marroquín', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Mariano Tagua Sánchez', 'dir' => 6, 'puesto' => 94],
            ['nombre' => 'Hugo Giovanni Barrientos Calderón', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Yaneth Glauser Oliva', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Carlos Fernando Rivera Cano', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Rosa Anabella Campos de León', 'dir' => 6, 'puesto' => 95],
            ['nombre' => 'Carlos Rene Rodriguez', 'dir' => 6, 'puesto' => 94],
            ['nombre' => 'Carlos Antulio Paz Mérida', 'dir' => 6, 'puesto' => 94],
            ['nombre' => 'Walter Leovardo Suc Ical', 'dir' => 6, 'puesto' => 94],
            ['nombre' => 'Josseline Andrea Aguilar Barillas', 'dir' => 6, 'puesto' => 95],

            /* Dirección de Logística */
            ['nombre' => 'Edy Rolando Ruíz García', 'dir' => 7, 'puesto' => 93],
            ['nombre' => 'Walter Arturo López Juárez', 'dir' => 7, 'puesto' => 92],
            ['nombre' => 'Ronald Josué Way Monterroso', 'dir' => 7, 'puesto' => 92],
            ['nombre' => 'Jennifer Beatriz Solares Ruano', 'dir' => 7, 'puesto' => 83],
            ['nombre' => 'Francisco Israél López López', 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Alejandro de Jesús Herrarte Ochoa', 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Guillermo Francisco Cabrera Marroquín', 'dir' => 7, 'puesto' => 17],
            ['nombre' => 'Genners Arturo Barrios Garay', 'dir' => 7, 'puesto' => 58],
            ['nombre' => 'Josué Calderón González', 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Lizandro Cano Cardona', 'dir' => 7, 'puesto' => 80],
            ['nombre' => 'Fernando José Paz González', 'dir' => 7, 'puesto' => 32],
            ['nombre' => 'Mario Ariel Ruiz Galindo', 'dir' => 7, 'puesto' => 61],
            ['nombre' => 'Miguel Anguel Aguilar Lara', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Rubén Antonio Avalos Ovalle', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Cesar Augusto Chur Cetino', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Gabriel Gamboa Sipac', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Alan Estuardo González Chávez', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Eber Rodolfo Pérez Cocón', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'José Domingo Prado Aroche', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Natanael Sian León', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Walter Estuardo Vásquez Marroquín', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Julio Anibal Yucuté Mijangos', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Miguel Arnoldo Zapeta Tobias', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Andy Gilberto Torres Camey', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Jorge Eduardo Carranza Cifuentes', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Byron Neftali Urizar Ayala', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Raul Alfredo Guzmán Vásquez', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Sergio Vinicio Donado Pérez', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Oscar Nolberto Ramos Ibañez', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Artemio Pérez y Pérez', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Rafael Neftalí Donis Torres', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Miguel Augusto Gudiel Alvarado', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Camilo Godoy Monzón', 'dir' => 7, 'puesto' => 94],
            ['nombre' => 'Josue Rafael Muñoz Rosales', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Danilo Estuardo Juarros Quinteros', 'dir' => 7, 'puesto' => 94],
            ['nombre' => 'Edwin Rolando Goméz Huertas', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Jonathan Benjamín Herrera Rodríguez', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Edgar David Franco Contreras', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Pedro Marcelo Habib Farfán Torres', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Alex René Rueda Valle', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Luis Estuardo Oliva Morales', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Kevin Jair Pantaleón Cordova Borrego', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Hector Antonio Donis del Cid', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'José Victor Díaz Juárez', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Julio Josué Valladares Cardona', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Jennifer Alicia Solares Aguilar', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Deivid Alexander Lud Revolorio', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Diego Andrés Obín Rosales', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Carlos Amilcar Flores Macario', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Brandon Alexander Reyes Oliveros', 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Julio César Jiménez Menéndez', 'dir' => 7, 'puesto' => 95],

            /* Inspectoria General */
            ['nombre' => 'María Alessandra del Rosario Izquierdo Flores', 'dir' => 8, 'puesto' => 93],
            ['nombre' => 'Anely Jazmin Tejada Cabachuela', 'dir' => 8, 'puesto' => 94],
            ['nombre' => 'Jennifer Paola Alvarez Arroyo', 'dir' => 8, 'puesto' => 94],
            ['nombre' => 'Ludsvin Francisco García Guitrón', 'dir' => 8, 'puesto' => 94],
            ['nombre' => 'Shirley Haydee García Hernández', 'dir' => 8, 'puesto' => 95],
            ['nombre' => 'Javier Alejandro Rodríguez Zea', 'dir' => 8, 'puesto' => 95],
            ['nombre' => 'Jefrey Josue Veliz Castellanos', 'dir' => 8, 'puesto' => 95],

            /* Unidad de Auditoría Interna */
            ['nombre' => 'Jackelinne Renata de Mata Marroquín', 'dir' => 9, 'puesto' => 91],
            ['nombre' => 'José Carlos Morales Masaya', 'dir' => 9, 'puesto' => 92],
            ['nombre' => 'Edgar Sebastián Montenegro Klee', 'dir' => 9, 'puesto' => 95],
            ['nombre' => 'Frankz Esaú Martínez Samayoa', 'dir' => 9, 'puesto' => 95],
            ['nombre' => 'Oscar Rolando Escobedo Aguilar', 'dir' => 9, 'puesto' => 94],
            ['nombre' => 'Mariano Alfredo Gonzalez Gutierrez', 'dir' => 9, 'puesto' => 94],

            /* Dirección de Recursos Humanos */
            ['nombre' => 'Marvin René Solorzano Tello', 'dir' => 10, 'puesto' => 93],
            ['nombre' => 'Lilian Aleyda Rojas Guzmán', 'dir' => 10, 'puesto' => 92],
            ['nombre' => 'Geimy Fabiola Vega Espina', 'dir' => 10, 'puesto' => 31],
            ['nombre' => 'Byron Enrique López Recinos', 'dir' => 10, 'puesto' => 36],
            ['nombre' => 'Leticia Eugenia Padilla Zuleta', 'dir' => 10, 'puesto' => 24],
            ['nombre' => 'Kattie Briana Alexandra Salazar Ortíz', 'dir' => 10, 'puesto' => 14],
            ['nombre' => 'Carlos Alberto Zuñiga y Zuñiga', 'dir' => 10, 'puesto' => 94],
            ['nombre' => 'Shirly Pamela De León López', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Josué Daniel Rosales Arché', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Ruth Pamela Rendón Martínez', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Wendy Catalina García Mejía', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Allan Francisco Platero Armas', 'dir' => 10, 'puesto' => 94],
            ['nombre' => 'Sergio Antonio Paiz Loarca', 'dir' => 10, 'puesto' => 94],
            ['nombre' => 'Evelyn Gabriela Mis Juárez', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Mirna Irasema Siliezar Tello', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Shirley Carolina Cardona Castillo', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Sergio Daniel Gonzáles López', 'dir' => 10, 'puesto' => 94],
            ['nombre' => 'Jenny Paola Lemus Temu', 'dir' => 10, 'puesto' => 95],
            ['nombre' => 'Sally del Carmen Maldonado Molina de Pedroza', 'dir' => 10, 'puesto' => 94],

            /* Dirección de Planificación y Desarrollo Institucional */
            ['nombre' => 'Carlota Lucía Cordón González', 'dir' => 11, 'puesto' => 93],
            ['nombre' => 'Sergio Estuardo Muñoz Rodriguez', 'dir' => 11, 'puesto' => 94],
            ['nombre' => 'Aleyda Noemi de León Pérez de López', 'dir' => 11, 'puesto' => 94],
            ['nombre' => 'Boris Rodrigo Gil Rivera', 'dir' => 11, 'puesto' => 95],
            ['nombre' => 'Luis Fernando Orozco Díaz', 'dir' => 11, 'puesto' => 95],
            ['nombre' => 'José Daniel Juárez Ortiz', 'dir' => 11, 'puesto' => 94],

            /* Unidad de Información Pública */
            ['nombre' => 'Marta María Valenzuela Rodríguez', 'dir' => 12, 'puesto' => 92],
            ['nombre' => 'Cindy Zucelly Quiñonez Izquierdo', 'dir' => 12, 'puesto' => 70],
            ['nombre' => 'Gabriela Renata Loyo Say', 'dir' => 12, 'puesto' => 95],

            /* Unidad de Asesoría Específica */
            ['nombre' => 'Alvaro Alejandro Cañas Lima', 'dir' => 13, 'puesto' => 92],
            ['nombre' => 'Josúe Daniel Veliz Hernández', 'dir' => 13, 'puesto' => 95],
            ['nombre' => 'Victor Manuel Ruano Hernández', 'dir' => 13, 'puesto' => 95],
            ['nombre' => 'Heidy Johanna Moscoso Calderón', 'dir' => 13, 'puesto' => 94],
            ['nombre' => 'Luis Gerardo Mendizábal Puac', 'dir' => 13, 'puesto' => 94],

            /* Dirección de Asesoría Jurídica */
            ['nombre' => 'Michelle Ninnette Alvarado López', 'dir' => 14, 'puesto' => 93],
            ['nombre' => 'Ana Sabrina Carballo Pinto', 'dir' => 14, 'puesto' => 95],
            ['nombre' => 'Ana Leticia Morales Vargas de Aragon', 'dir' => 14, 'puesto' => 94],
            ['nombre' => 'Manuel Humberto Monroy Ovalle', 'dir' => 14, 'puesto' => 94],
            ['nombre' => 'Jose Adolfo Guillermo Martinez Lucero', 'dir' => 14, 'puesto' => 94],
            ['nombre' => 'Edgar Geovany López Muñoz', 'dir' => 14, 'puesto' => 94],
            ['nombre' => 'María Gabriela Chang Salazar', 'dir' => 14, 'puesto' => 94],
            ['nombre' => 'Hugo Geovanni Meza Loarca', 'dir' => 14, 'puesto' => 94],

            /* Unidad de Género */
            ['nombre' => 'Marlyn Jeazbeth Cano Marroquín', 'dir' => 15, 'puesto' => 91],
            ['nombre' => 'Dolores Raquel López Gómez', 'dir' => 15, 'puesto' => 95],

            /* Dirección de Gestión Integral de Reducción de Riesgos a Desastres */
            ['nombre' => 'Irasema Dilián Magaña Muñoz', 'dir' => 16, 'puesto' => 93],
            ['nombre' => 'Guido Armando Barillas Quezada', 'dir' => 16, 'puesto' => 44],
            ['nombre' => 'Ana Cristina López Bonilla', 'dir' => 16, 'puesto' => 63],
            ['nombre' => 'Erick Eduardo Girón García', 'dir' => 16, 'puesto' => 16],
            ['nombre' => 'Hernán Turcios Castro', 'dir' => 16, 'puesto' => 43],
            ['nombre' => 'Juan Francisco Alvarez Estrada', 'dir' => 16, 'puesto' => 42],
            ['nombre' => 'Ericka Vidalí Jiménez Suriano', 'dir' => 16, 'puesto' => 83],
            ['nombre' => 'María José Calderón Cordero', 'dir' => 16, 'puesto' => 95],
            ['nombre' => 'Lorena Ninel Estrada Chinchilla', 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'César Antonio Erazo Cruz', 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'Luisa Fernanda Sánchez Gómez', 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'Mario Roberto Cabrera Pérez', 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'Josué David Ovando Arreaga', 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'Miguel Angel Estada Méndez', 'dir' => 16, 'puesto' => 95],

            /* Dirección de Mitigación */
            ['nombre' => 'David Anibal Moterroso Juárez', 'dir' => 17, 'puesto' => 93],
            ['nombre' => 'Hardany Ezequiel Navarro Miranda', 'dir' => 17, 'puesto' => 38],
            ['nombre' => 'Helbert Rolando de León Samayoa', 'dir' => 17, 'puesto' => 35],
            ['nombre' => 'Andrea Celeste Estrada Aguilar', 'dir' => 17, 'puesto' => 83],
            ['nombre' => 'Nelson Abraham Ramírez López', 'dir' => 17, 'puesto' => 37],
            ['nombre' => 'Wanderley Roberto Pérez Galdamez', 'dir' => 17, 'puesto' => 56],
            ['nombre' => 'Ana Cristina Rodriguez Alvarado', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Massiel Rodríguez Rustrián', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Gabriela Teresa Villagran Cano', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Hessel Mabel Mancilla Cojolún de Cordoba', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Susan Jeaneth Godoy Corzo', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Andrea Margarita Smith López', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'José Roberto Filippi Arriaga', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Carlos Manuel Beteta Lobos', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Katherinne Alcira Samayoa Boteo', 'dir' => 17, 'puesto' => 95],
            ['nombre' => 'Andrea Eunice Gutiérrez García', 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Norma Verónica Monroy Rodríguez', 'dir' => 17, 'puesto' => 94],

            /* Dirección de Preparación */
            ['nombre' => 'Alberto Herrera Ordóñez', 'dir' => 18, 'puesto' => 93],
            ['nombre' => 'Hilda Maribel Bajxac Chile', 'dir' => 18, 'puesto' => 92],
            ['nombre' => 'Helen Carolina Escobar Fernandez de García', 'dir' => 18, 'puesto' => 92],
            ['nombre' => 'Alejandra Morales Samayoa', 'dir' => 18, 'puesto' => 29],
            ['nombre' => 'Ingrid Julisa Lorenzana Cotto', 'dir' => 18, 'puesto' => 50],
            ['nombre' => 'Katherin Sofía Juárez Jordán', 'dir' => 18, 'puesto' => 40],
            ['nombre' => 'Nidia Eunice Díaz Morales de Fallas', 'dir' => 18, 'puesto' => 26],
            ['nombre' => 'Gabriel Fernando Oliva Hernández', 'dir' => 18, 'puesto' => 59],
            ['nombre' => 'Gamaliel Folgar Lucas', 'dir' => 18, 'puesto' => 95],
            ['nombre' => 'Jeniffer Aime Flores López', 'dir' => 18, 'puesto' => 95],
            ['nombre' => 'Salvador Elías Paredes Martínez', 'dir' => 18, 'puesto' => 94],
            ['nombre' => 'Rodelby Adelso Pérez Gálvez', 'dir' => 18, 'puesto' => 95],
            ['nombre' => 'Elmer Arnoldo Alarcón Arredondo', 'dir' => 18, 'puesto' => 95],

            /* Dirección de Respuesta */
            ['nombre' => 'Paul René Ugarte Estrada', 'dir' => 19, 'puesto' => 93],
            ['nombre' => 'Eduardo Luis Aguilar Flores', 'dir' => 19, 'puesto' => 92],
            ['nombre' => 'Minor Abraham Marroquín López', 'dir' => 19, 'puesto' => 92],
            ['nombre' => 'Virginia Alejandra Orellana Molina', 'dir' => 19, 'puesto' => 74],
            ['nombre' => 'Pedropablo Castañeda Ramírez', 'dir' => 19, 'puesto' => 74],
            ['nombre' => 'Dunia Cecibel Recinos Fabian', 'dir' => 19, 'puesto' => 68],
            ['nombre' => 'Mel Aparicio García', 'dir' => 19, 'puesto' => 79],
            ['nombre' => 'Dina Lucrecia Reyes Tejada', 'dir' => 19, 'puesto' => 79],
            ['nombre' => 'Benjamín Taumaturgo Lara Juárez', 'dir' => 19, 'puesto' => 79],
            ['nombre' => 'Luis Armando Recinos del Valle', 'dir' => 19, 'puesto' => 84],
            ['nombre' => 'Josselinne Anabel Mazariegos Barrios de Montes', 'dir' => 19, 'puesto' => 84],
            ['nombre' => 'Liseth Dalila Peña González', 'dir' => 19, 'puesto' => 64],
            ['nombre' => 'Mildred Magaly Castañeda Hernández', 'dir' => 19, 'puesto' => 47],
            ['nombre' => 'Bairon Alejandro Rosales Rodriguez', 'dir' => 19, 'puesto' => 15],
            ['nombre' => 'Hugo Armando Sinay López', 'dir' => 19, 'puesto' => 85],
            ['nombre' => 'María del Carmen López Lima', 'dir' => 19, 'puesto' => 85],
            ['nombre' => 'Lourdes Carolina Dardon Barillas', 'dir' => 19, 'puesto' => 85],
            ['nombre' => 'Erick Eduardo Castro Cas', 'dir' => 19, 'puesto' => 85],
            ['nombre' => 'Juan Jilmar Delgado Zacarías', 'dir' => 19, 'puesto' => 85],
            ['nombre' => 'Jorge Mario Jr. Herrera Escobar', 'dir' => 19, 'puesto' => 87, 'regional' => 1],
            ['nombre' => 'José Antonio Benitez Colomo', 'dir' => 19, 'puesto' => 88, 'regional' => 1, 'regional' => 1],
            ['nombre' => 'Edgar Anibal Aguirre Sandoval', 'dir' => 19, 'puesto' => 90, 'regional' => 1],
            ['nombre' => 'Oliver José Castañeda Barrera', 'dir' => 19, 'puesto' => 85],
            ['nombre' => 'Jorge Jafeth Rodríguez López', 'dir' => 19, 'puesto' => 84],
            ['nombre' => 'Juan Gabriel Samayoa Bolaños', 'dir' => 19, 'puesto' => 65],
            ['nombre' => 'Byron Fernando Quiroa Villanueva', 'dir' => 19, 'puesto' => 66],
            ['nombre' => 'Luis Alberto Pelaéz Méndez', 'dir' => 19, 'puesto' => 84],
            ['nombre' => 'Julio Rafael Quintanilla Coronado', 'dir' => 19, 'puesto' => 21],
            ['nombre' => 'Kevin Gabriel Velásquez López', 'dir' => 19, 'puesto' => 84],
            ['nombre' => 'Luis Antonio Cajas Juárez', 'dir' => 19, 'puesto' => 5],
            ['nombre' => 'Heidy Marisela Baínas Sanes de Escobar', 'dir' => 19, 'puesto' => 83],
            ['nombre' => 'Osmar Omar Crúz Arbizú', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Wilder Omar Rodríguez Pérez', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Jorge Alfredo Rivas Zeceña ', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Ingrid Geraldina Sagastume Reyes', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Myrna Angélica Mejía Alonzo', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Kevin Estuardo Escobar Solares', 'dir' => 19, 'puesto' => 95, 'regional' => 1],
            ['nombre' => 'Ana Luisa Hernández Cardona', 'dir' => 19, 'puesto' => 94, 'regional' => 1],
            ['nombre' => 'Gustavo Anibal Archila Paz', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Karen Daniela Oliva Guerra', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Juan Luis Santos Caceres', 'dir' => 19, 'puesto' => 95, 'regional' => 1],
            ['nombre' => 'Roberto Antonio Recinos Morales', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Hugo Alfredo García Leiva', 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Grisselda Carolina Arévalo Guzmán', 'dir' => 19, 'puesto' => 95],

            /* Dirección de Recuperación */
            ['nombre' => 'Cesar Estuardo Micheo López', 'dir' => 20, 'puesto' => 93],
            ['nombre' => 'Luis Humberto Ligorría Molina', 'dir' => 20, 'puesto' => 92],
            ['nombre' => 'Néricci Giuseppe Salazar Santos', 'dir' => 20, 'puesto' => 23],
            ['nombre' => 'Vivian Alejandra Jorge Posadas', 'dir' => 20, 'puesto' => 95],
            ['nombre' => 'Marvin Eduardo Noriega Vielman', 'dir' => 20, 'puesto' => 94],
            ['nombre' => 'Shirley Oddet Medrano Palma', 'dir' => 20, 'puesto' => 95],
            ['nombre' => 'Paola Xiomara Barrios Estrada', 'dir' => 20, 'puesto' => 94],
            ['nombre' => 'Luis Mario Montenegro Osorio', 'dir' => 20, 'puesto' => 94],
            ['nombre' => 'Katherine Elizabeth Gómez Turcios', 'dir' => 20, 'puesto' => 94],
            ['nombre' => 'Luis Alberto Méndez González', 'dir' => 20, 'puesto' => 94],

            /* Dirección de Sistema de Comando de Incidentes */
            ['nombre' => 'Iván Felipe de Jesús Mazariegos Núñez', 'dir' => 21, 'puesto' => 93],
            ['nombre' => 'Marlon Rigoberto Mayén Cifuentes', 'dir' => 21, 'puesto' => 92],
            ['nombre' => 'Allan Kenny Martínez Quiñonez', 'dir' => 21, 'puesto' => 92],
            ['nombre' => 'Rómulo Andres Mejía Villatoro', 'dir' => 21, 'puesto' => 13],
            ['nombre' => 'Edson Francisco Sandoval Gálvez', 'dir' => 21, 'puesto' => 39],
            ['nombre' => 'Edwin Antonio Pérez Burrión', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Luis Enrique González Xoyón', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Elmar Javier Pérez Marroquín', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Josue Cristobal Guzmán Tello', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Mynor Josué Curumaco Moya', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'José Manolo García Pérez', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Hugo Francisco Escobar Fuentes', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Josie Rosmary Diéguez Velásquez', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Efraín Fernando Cerna Mendoza', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Marvin David Rodriguez Morales', 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'José Francisco Morales Galdámez', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Sergio Rolando De La Cruz Gómez', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Rodimiro Vargas García', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Cecilio Florindo Alvarado Alvarado', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Delsy Migdalia Ramos Lemus', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Carlos Jiménez Sales', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Marcia Jazmin Patricia Romero González', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Kinberly Michel Juárez García', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Francisco Antonio López Salas', 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Alfredo Edberto López Sipaque', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Mynor Estuardo Ramírez De León', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Edy Alejandro Castañeda Yocute', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Eliezer Andres Maas Dávila', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Celso Joaquín Vásquez Velásquez', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Mario Rosendo Patzán Oscal', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Neida Teresa Chivichón Hernández', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Luis Fernando Polanco Muralles', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Francisco Sachariel Itzamna Chávez López', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Steffany Noemí Sacalxot Chial', 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Malín Graciela Cifuentes Pellecer', 'dir' => 21, 'puesto' => 97],

            /* Dirección de Comunicación Social */
            ['nombre' => 'Carlos Andrés Erazo Barreda', 'dir' => 22, 'puesto' => 93],
            ['nombre' => 'Nivea María Eunice Solares Bolaños de Rosemberg', 'dir' => 22, 'puesto' => 92],
            ['nombre' => 'Ana Cristina Cifuentes Legrand', 'dir' => 22, 'puesto' => 25],
            ['nombre' => 'Chrystian Javier Contreras Barrios', 'dir' => 22, 'puesto' => 48],
            ['nombre' => 'Mónica Marleny Escobar López', 'dir' => 22, 'puesto' => 11],
            ['nombre' => 'Javier Stuardo Santizo Galán', 'dir' => 22, 'puesto' => 76],
            ['nombre' => 'Rudy Alexander Pérez Ajanel', 'dir' => 22, 'puesto' => 19],
            ['nombre' => 'Carlos Enrique Mendoza López', 'dir' => 22, 'puesto' => 49],
            ['nombre' => 'Indara María Dolores Amado Ortíz de Martínez', 'dir' => 22, 'puesto' => 94],
            ['nombre' => 'Alejandra María Meda Calderón', 'dir' => 22, 'puesto' => 94],
            ['nombre' => 'Elda Lissette Jordán Ordoñez de Balcarcel', 'dir' => 22, 'puesto' => 94],
            ['nombre' => 'Elíazar Martínez Caceres', 'dir' => 22, 'puesto' => 95],
            ['nombre' => 'Astrid Paola Rodríguez Manzo', 'dir' => 22, 'puesto' => 94],
            ['nombre' => 'Maria Paula Salguero Arana', 'dir' => 22, 'puesto' => 95],
            ['nombre' => 'Rodolfo Enrique García Méncos', 'dir' => 22, 'puesto' => 94],
            ['nombre' => 'Lued Vivianalucía Bran Barrios', 'dir' => 22, 'puesto' => 95],
            ['nombre' => 'Claudia Lucia Paz Castellanos', 'dir' => 22, 'puesto' => 94],
            ['nombre' => 'Paulina Beatriz Marroquín Higueros', 'dir' => 22, 'puesto' => 95],

            /* Region II */
            ['nombre' => 'Franklin de Jesús Choc Salam', 'reg' => 2, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Sergio Estuardo Solares García', 'reg' => 2, 'dir' => 16, 'puesto' => 81],
            ['nombre' => 'Pablo Antonio Bailón Leonardo', 'reg' => 2, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Carlos René Meléndez López', 'reg' => 2, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Sergio Alejandro Valdez Paredes', 'reg' => 2, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'José Manuel Chavarría Iglesias', 'reg' => 2, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Cristian Josué Chen Juárez', 'reg' => 2, 'dir' => 18, 'puesto' => 95],
            ['nombre' => 'Londy Azucena Mejía Ajcucún', 'reg' => 2, 'dir' => 20, 'puesto' => 94],
            ['nombre' => 'Matías Figueroa Hernández', 'reg' => 2, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Rudy Waldemar Morales Soberanis', 'reg' => 2, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Esler Wilfredo Castro Reinoso', 'reg' => 2, 'dir' => 19, 'puesto' => 78],
            ['nombre' => 'Byron Amado de Jesús Caal Bol', 'reg' => 2, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'José Esteban Morales Barrientos', 'reg' => 2, 'dir' => 19, 'puesto' => 86],
            ['nombre' => 'César Wotzbely Suárez Villatoro', 'reg' => 2, 'dir' => 19, 'puesto' => 87],
            ['nombre' => 'Rafael Antonio Choc Blanco', 'reg' => 2, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'José David Pérez Chenal', 'reg' => 2, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Gustavo Haroldo López López', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Angel Gerardo Ruiz Valdéz', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Victor Marroquín Marroquin', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'César Augusto Pérez García', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Oscar Fernando Caal Tut', 'reg' => 2, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Carlos Ixcopal', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Niesel Ariel Xol Chiquin', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Daniel Antonio Corado Guerrero', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Yonatan Guadalupe Franco Aceituno', 'reg' => 2, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Victor Hugo Xoná Caal', 'reg' => 2, 'dir' => 21, 'puesto' => 96],

            /* Región III */
            ['nombre' => 'Yuliana Izabel Vargas Sosa', 'reg' => 3, 'dir' => 19, 'puesto' => 86],
            ['nombre' => 'Carlos Humberto Godoy Monzón', 'reg' => 3, 'dir' => 19, 'puesto' => 87],
            ['nombre' => 'Pablo Enríquez Pérez', 'reg' => 3, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Jefferson Roberto Sandoval Quezada', 'reg' => 3, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Franklin Yovany Maldonado López', 'reg' => 3, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Mayra Violeta Arévalo Gómez', 'reg' => 3, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Andrea Massiell León Chacón', 'reg' => 3, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'Marvin Omar Lemus Paiz', 'reg' => 3, 'dir' => 19, 'puesto' => 86],
            ['nombre' => 'Alberto Augusto Palma Ramírez', 'reg' => 3, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'Elsa María Morales Chacón', 'reg' => 3, 'dir' => 19, 'puesto' => 81],
            ['nombre' => 'María Fernanda Ordóñez Polanco', 'reg' => 3, 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Luisa Karina Rossal Aragón', 'reg' => 3, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Julio Alberto Franco Flores', 'reg' => 3, 'dir' => 17, 'puesto' => 95],
            ['nombre' => 'Marco Antonio Lobos Rivera', 'reg' => 3, 'dir' => 17, 'puesto' => 95],
            ['nombre' => 'José Carlos Guerra Pineda', 'reg' => 3, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Jesús Albeto Casasola Chacón', 'reg' => 3, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Jaime Orlando Landaverry Guerra', 'reg' => 3, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Oscar Geovani Leonardo', 'reg' => 3, 'dir' => 7, 'puesto' => 80],
            ['nombre' => 'Ramón Gutiérrez Aldana', 'reg' => 3, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Nery Aldana Leiva', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Marco Tulio Leiva Arriaza', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Manuel Antonio Campos Asencio', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'William Alexander Pérez y Pérez', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Martín Pérez y Pérez', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Juan Carlos Pacheco Herrera', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Mario Alexander Barcenas', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Belter José Monroy Vásquez', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Juan Carlos Gómez Pérez', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Cristofer Orlando Sánchez López', 'reg' => 3, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Gabriel Antonio Palencia', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Oscar Vásquez Picón', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Christian Geovany Caal Ortega', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Domingo Aroche Bautista', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Luis René Colindres Monroy', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Guillermo López Galicia', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Carlos Enrique Ovaye López', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Gerson Yovani Marroquín Jiménez', 'reg' => 3, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Alvaro Arnoldo García Arroyo', 'reg' => 3, 'dir' => 21, 'puesto' => 96],

            /* Región IV */
            ['nombre' => 'María Jimena Ortega Marroquín', 'reg' => 4, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Estuardo Giovanni Reyes Orozco', 'reg' => 4, 'dir' => 16, 'puesto' => 81],
            ['nombre' => 'Brandon Omar García Colindres', 'reg' => 4, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Lester Alfonso Cartagena Juárez', 'reg' => 4, 'dir' => 19, 'puesto' => 86],
            ['nombre' => 'Riniwed Renato Echeverría León', 'reg' => 4, 'dir' => 19, 'puesto' => 87],
            ['nombre' => 'José Adolfo Bolaños Amaya', 'reg' => 4, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Virgilio Alvaro Ramírez García', 'reg' => 4, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Elder Humberto Juárez', 'reg' => 4, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Cristian Alexander Estrada Arana', 'reg' => 4, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Edwin Alexander Cuellar Valladares', 'reg' => 4, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Santos Eduardo Hernández Mateo', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José William Rodríguez Mateo', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Eraldo Pérez Martínez', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Amicar Ezquiel De La Rosa Díaz', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Henry Rubí Raymundo Cruz', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Alberto Antonio Mateo Hernández', 'reg' => 4, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Roberto Antonio López Nájera', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Francisco Jilberto Aguilar Jerónimo', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Mariano Castillo Jiménez', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Rudy Obdulio Gomez Lorenzo', 'reg' => 4, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Oscar Andrés García Armas', 'reg' => 4, 'dir' => 21, 'puesto' => 95],

            /* Región V */
            ['nombre' => 'Ottoniel Rodríguez Ajquí', 'reg' => 5, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Sóstenes Rocael Pimentel Avila', 'reg' => 5, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Victor Andres Quiñonez Aguilar', 'reg' => 5, 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'Eduardo Sánchez Díaz', 'reg' => 5, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Héctor Ramiro Sicajau Hernández', 'reg' => 5, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Edgar Benjamín Xar Valle', 'reg' => 5, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Francisco Rivas Enriquez', 'reg' => 5, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Nery Alberto Díaz Abac', 'reg' => 5, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Cristian Alexander Vásquez González', 'reg' => 5, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Mauricio Esteban García Camey', 'reg' => 5, 'dir' => 18, 'puesto' => 95],
            ['nombre' => 'Pedro Luis Marroquín Ixmatul', 'reg' => 5, 'dir' => 20, 'puesto' => 95],
            ['nombre' => 'Cesar Ernesto Bethancourt De León', 'reg' => 5, 'dir' => 20, 'puesto' => 52],
            ['nombre' => 'Carlos Roberto Ruíz Larios', 'reg' => 5, 'dir' => 19, 'puesto' => 86],
            ['nombre' => 'Edgar Felipe Ramos Sagastume', 'reg' => 5, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'Manuel Fernando López Hora', 'reg' => 5, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'William Francisco Chigna Yuque', 'reg' => 5, 'dir' => 19, 'puesto' => 46],
            ['nombre' => 'Mario Efraín Ovalle Hernández', 'reg' => 5, 'dir' => 19, 'puesto' => 82],
            ['nombre' => 'Jorge Luis Mejicanos Reyes', 'reg' => 5, 'dir' => 19, 'puesto' => 82],
            ['nombre' => 'Dora Briseida Salpec Palma', 'reg' => 5, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Carlos Antonio Gamboa De León Regil', 'reg' => 5, 'dir' => 19, 'puesto' => 87],
            ['nombre' => 'Erwin Landelino Hernández Lima', 'reg' => 5, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Daniel Estuardo Guerra Carrera', 'reg' => 5, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Carlos Anibal Ajvix Alonzo', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Miguel Angel Moxín Machic', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Juan Valentin Puz Tala', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Carlos Enrique Sal Alvarez', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Wilfredo Sinay Chamalé', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Humberto Adolfo Chiriz Siquinajay', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Edy Francisco Otzín Tuyuc', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Paulino Suy Chiroy', 'reg' => 5, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Edy Daniel Mendoza Jalles', 'reg' => 5, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Kevin José Chonay Calel', 'reg' => 5, 'dir' => 21, 'puesto' => 96],

            /* Region VI */
            ['nombre' => 'Boyer Byron Garcia Santos', 'reg' => 6, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Edínson Aristeo De León Gómez', 'reg' => 6, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Donal Leonel Romero Archila', 'reg' => 6, 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'Rodolfo Carlos Guzmán Jiménez', 'reg' => 6, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Edvin Osbaldo López Salazar', 'reg' => 6, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Jesús Morales Recinos', 'reg' => 6, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Francisco Enrique Miranda López', 'reg' => 6, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Nevin Eliezer López López', 'reg' => 6, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Etzon Roberto Rojas Sacor', 'reg' => 6, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Sergio Roberto Mérida Fuentes', 'reg' => 6, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Jeymy Clara Luz Aragón de Paz', 'reg' => 6, 'dir' => 18, 'puesto' => 94],
            ['nombre' => 'Eliza Cristina Salanic Coti', 'reg' => 6, 'dir' => 18, 'puesto' => 94],
            ['nombre' => 'Erwin Salvatore Mérida López', 'reg' => 6, 'dir' => 20, 'puesto' => 95],
            ['nombre' => 'Sabrina Celeste Elias Ajcá', 'reg' => 6, 'dir' => 20, 'puesto' => 94],
            ['nombre' => 'Rafael Humberto Zoc Flores', 'reg' => 6, 'dir' => 19, 'puesto' => 86],
            ['nombre' => 'Sandino Monzón García', 'reg' => 6, 'dir' => 19, 'puesto' => 87],
            ['nombre' => 'Francisco Moisés Cajas Toledo', 'reg' => 6, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Pedro Luis Pérez', 'reg' => 6, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Manuel Bernardo Zapeta Montejo', 'reg' => 6, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Gustavo Adolfo Arana Jui', 'reg' => 6, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Edy Juan José Maldonado Moreno', 'reg' => 6, 'dir' => 19, 'puesto' => 82],
            ['nombre' => 'Manlio Salomón Lec Sicay', 'reg' => 6, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Yener Oswaldo Pelicó Pérez', 'reg' => 6, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'José Francisco Alfaro Maldonado', 'reg' => 6, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Mayra Nohemí Salanic Joj', 'reg' => 6, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Jorge Eduardo Quezada Pimentel', 'reg' => 6, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Pedro Isaías Más Bac', 'reg' => 6, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Franz Igor Kiss Velásquez', 'reg' => 6, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Vivian Marcela Consuegra Bautista', 'reg' => 6, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Esdras Miguel Canastuj García', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Milthon Abener Ixcaquic Socop', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Ovidio Miguel Yax Velásquez', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Anibal De León Tzul', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Marlon Geovany Leiva Vargas', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Francisco Gómez Chacaj', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Vicente Mendoza Cojtín', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Jersson Alejandro Par Pérez', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Abelino Cuxulíc Tzorín', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Oscar Alfredo Ajcalón Quiché', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Emilio Chipín Bixcul', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Rodrigo Quisquiná García', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Eduardo Antonio Chorol Chiyal', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Gober Alexander Píc Tzay', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Pedro Antonio Bocel Par', 'reg' => 6, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Fredy Armando Alvarado Xuruc', 'reg' => 6, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Domingo Geovanni García Utuy', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Nehemías Nicolás García Bulux', 'reg' => 6, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Daniel de Jesús Nimatuj Estacuy', 'reg' => 6, 'dir' => 21, 'puesto' => 95],

            /* Región VII */
            ['nombre' => 'Nátaly Idania Anahí Ibáñez Sánchez', 'reg' => 7, 'dir' => 16, 'puesto' => 81],
            ['nombre' => 'José Virgilio Tello Tello', 'reg' => 7, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Erwin Federico Wellmann Gómez', 'reg' => 7, 'dir' => 7, 'puesto' => 80],
            ['nombre' => 'Alejandro Carillo Mendoza', 'reg' => 7, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Hugo David Natarenos Barrios', 'reg' => 7, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Walter Francisco López Ramos', 'reg' => 7, 'dir' => 18, 'puesto' => 95],
            ['nombre' => 'César Ariel Beltrán Herrera', 'reg' => 7, 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Juan Carlos Palacios Féliz', 'reg' => 7, 'dir' => 20, 'puesto' => 94],
            ['nombre' => 'Gustavo Adolfo Rojas López', 'reg' => 7, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'Jorge Stuardo Méndez Recinos', 'reg' => 7, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Pablo Daniel Cobón Villatoro', 'reg' => 7, 'dir' => 19, 'puesto' => 87],
            ['nombre' => 'Idalia Marianela Esteban Castillo de Quezada', 'reg' => 7, 'dir' => 19, 'puesto' => 86],
            ['nombre' => 'Eladio Miguel Xirúm Salvador', 'reg' => 7, 'dir' => 19, 'puesto' => 90],
            ['nombre' => 'Antonio Hilcías Ixcotoyac Cabrera', 'reg' => 7, 'dir' => 19, 'puesto' => 78],
            ['nombre' => 'José Roberto Solares Cordón', 'reg' => 7, 'dir' => 19, 'puesto' => 95],
            ['nombre' => 'Walter Mardoqueo Muñoz Sánchez', 'reg' => 7, 'dir' => 19, 'puesto' => 94],
            ['nombre' => 'José Raúl Morales Martínez', 'reg' => 7, 'dir' => 19, 'puesto' => 94],
            ['nombre' => 'Aniseto Edilsar Gómez Gómez', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Miguel Alisandro Martínez Gómez', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Wotzbelli Arcenio Carrillo López', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Elder Amilcar Vásquez Gómez', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Marino Bersain Martínez Ramos', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Martín Ventura Zapeta', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Regino Ramos Chich', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Rony Mateo Ventura Ventura', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Enrvin Rolando Carrera Mazariegos', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Oswaldo Caba Ortega', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Sebastián Ventura Jerónimo', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Benkler Yusvan Garcia Hidalgo', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Fernando Larios Zapeta', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Diego Jorge Ventura', 'reg' => 7, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Dennys Heriberto Rodríguez Hernández', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Israel José David Soto Urízar', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Wilson Santiago García López', 'reg' => 7, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Alvaro Virgilio Fabián Luis', 'reg' => 7, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Henry Omar Galindo Avila', 'reg' => 7, 'dir' => 21, 'puesto' => 95],

            /* Región VIII */
            ['nombre' => 'Oscar Germán Cano Guillermo', 'reg' => 8, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Salvador Felipe Neri Caal Chocoj', 'reg' => 8, 'dir' => 4, 'puesto' => 95],
            ['nombre' => 'Sergio Francisco Pérez De Luca', 'reg' => 8, 'dir' => 16, 'puesto' => 94],
            ['nombre' => 'Jónathan Arturo Mejía Hernández', 'reg' => 8, 'dir' => 7, 'puesto' => 89],
            ['nombre' => 'Fernando Antonio López Cano', 'reg' => 8, 'dir' => 7, 'puesto' => 95],
            ['nombre' => 'Josué Mario Saavedra Reyes', 'reg' => 8, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Maryori Dalissa Rodríguez Borjes', 'reg' => 8, 'dir' => 17, 'puesto' => 94],
            ['nombre' => 'Hugo René Junior Rivera Marroquín', 'reg' => 8, 'dir' => 18, 'puesto' => 94],
            ['nombre' => 'Oscar Geovany Zetina Tún', 'reg' => 8, 'dir' => 19, 'puesto' => 88],
            ['nombre' => 'Francisco Javier Guzman Herrera', 'reg' => 8, 'dir' => 19, 'puesto' => 87],
            ['nombre' => 'Osvaldo Mauiricio Guerra Quixchán', 'reg' => 8, 'dir' => 4, 'puesto' => 90],
            ['nombre' => 'Anibal Fernando Quixchán Chí', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Seíner Melitón Zacal Perez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Gedor Neonel Gutierrez Sintuj', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Auder Alexander González Castillo', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Carlos Humberto Hernández Pérez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Jesús Alexsander Chablé Ramírez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Nemrod Alanquenis Juárez Castillo', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Victor Gerardo Gúzman Herrera', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Hugo Yaxcal Tzi', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Angel Gabriel Cu Macs', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Julio René Moscoso Mayorga', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Juan Montejo Velasco', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Arnulfo Girón Godoy', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Rodolfo Humberto Caal Teyul', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Juan Carlos Ruíz Balcárcel', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Josué Nehemias Esquivel Ramírez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Adan Bol Tiul', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Saul Heliodoro Leodegario Chub Coy', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Yoni Wanelger Bolaños Sánchez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Franklin Alexander Reinoso Ramírez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Yelsin Oseas Quixchán Raymundo', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Anibal Fernando Quixchán Chí', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Pedro Leonel Morales Samos', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Byron Ronaldo Pacay Qujevedo', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Samuel Otoniel Luna Morales', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Marvin Israel García Ruano', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Julio Aroldo Pineda Ramírez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Humberto Israel Castañaza Cruz', 'reg' => 8, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'César Waldemar Mayén Orrego', 'reg' => 8, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Oscar Guerra Rivera', 'reg' => 8, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Juan Oseas Mes Chohuoj', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'José Antonio Juárez', 'reg' => 8, 'dir' => 21, 'puesto' => 97],
            ['nombre' => 'Jhónatan Ezequiel Ordóñez Leonardo', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Edwin Rolando Hernández Miranda', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Alfredo Bulún Xoj', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Darlo Maudiel López Juárez', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'César David Zac Bonilla', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Elías Natanael Chávez García', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Anderson Osiel Gutiérrez Tzir', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Darlyn Abel Aguirre Peraza', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Manuel Chub Teec', 'reg' => 8, 'dir' => 21, 'puesto' => 96],
            ['nombre' => 'Josias Masiel Santiago Cortéz', 'reg' => 8, 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Carlos Francisco Zetina Acosta', 'reg' => 8, 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Sergio Rodolfo Tzin Gómez', 'reg' => 8, 'dir' => 21, 'puesto' => 95],
            ['nombre' => 'Reyna Magdalena Vásquez Perez', 'reg' => 8, 'dir' => 19, 'puesto' => 88],
        ];

        foreach ($empleados as $emp) {
            $regionId = isset($emp['reg']) ? $emp['reg'] : 1;
            $regional = isset($emp['regional']) ? $emp['regional'] : 0;

            $empleado = PirEmpleado::create([
                'nombre' => $emp['nombre'],
                'pir_direccion_id' => $emp['dir'],
                'region_id' => $regionId,
                'is_regional_i' => $regional
            ]);

            PirPuesto::create([
                'pir_empleado_id' => $empleado->id,
                'catalogo_puesto_id' => $emp['puesto']
            ]);
        }
    }
}
